-- =====================================================================
-- 2026-08-08 — two system email templates that had no send point until now
--
-- VISIT_CAMPUS_REJECTED             a Staff Leader declines ONE campus -> the registrant is told
--                                   which campus and why. Scoped to that campus on purpose: the
--                                   request may still be waiting on, or accepted by, its siblings.
-- VISIT_CONTACT_INVITATION_EXPIRED  a contact invitation (INITIAL_CONFIRMATION 72h / TRANSFER 24h)
--                                   lapsed unanswered -> the registrant is told, because only they
--                                   can resend it or name somebody else.
--
-- Additive and idempotent: INSERT ... ON DUPLICATE KEY UPDATE on template_code, so re-running
-- converges instead of erroring, and an operator's own edits to an existing row are overwritten
-- only for these two codes.
--
-- Rollback: DELETE FROM email_templates WHERE template_code IN (...) and the matching
--           email_contact_policies rows. Nothing references them by id.
-- =====================================================================

INSERT INTO email_templates
  (email_template_id, template_code, name, purpose, campus_id, description,
   status, subject_vi, body_vi, subject_en, body_en, body_format, variables_text,
   created_at, created_by, updated_at, updated_by)
VALUES
  (70032, 'VISIT_CAMPUS_REJECTED', 'Thông báo cơ sở từ chối tiếp nhận', 'VISIT_REQUEST', NULL, 'Gửi người đăng ký khi một cơ sở từ chối tiếp nhận đoàn. Phạm vi đúng một cơ sở: các cơ sở khác của cùng yêu cầu không bị ảnh hưởng.', 'ACTIVE',
   '[PEMS] Cơ sở {{campusName}} chưa thể tiếp nhận yêu cầu {{requestCode}}', '<p style="margin:0 0 16px;color:#334155">Kính gửi <strong>{{recipientName}}</strong>,</p><p style="margin:0 0 14px;color:#334155;line-height:1.65">Rất tiếc, cơ sở <strong>{{campusName}}</strong> chưa thể tiếp nhận đoàn của Quý vị trong yêu cầu dưới đây. Các cơ sở khác trong cùng yêu cầu (nếu có) không bị ảnh hưởng bởi quyết định này.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;margin:18px 0;border:1px solid #dbe4ee;border-radius:8px"><tbody><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Mã yêu cầu</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{requestCode}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Đoàn</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{delegationName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Cơ sở</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{campusName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%">Thời gian dự kiến</td><td style="padding:10px 14px;font-weight:600;color:#334155">{{plannedTime}}</td></tr></tbody></table><div style="margin:20px 0;padding:16px 18px;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px"><p style="margin:0 0 8px;font-weight:700;color:#9a3412">Lý do từ chối</p><p style="margin:0;color:#334155;line-height:1.6">{{reason}}</p></div><p style="margin:0 0 14px;color:#334155;line-height:1.65">Quý vị có thể chỉnh sửa và gửi lại yêu cầu trong trang quản lý yêu cầu tham quan. Lưu ý lịch gửi lại cần cách thời điểm gửi ít nhất 72 giờ.</p><div style="margin:20px 0 0;padding:14px 16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px"><p style="margin:0 0 8px;font-size:12px;font-weight:700;color:#475569">Thông tin người gửi</p><p style="margin:0;line-height:1.65;color:#334155"><strong>{{senderName}}</strong><br/>{{senderRole}}<br/>{{senderDepartment}}<br/>{{senderEmail}}</p></div><p style="margin:22px 0 0;color:#64748b;font-size:12px;line-height:1.6">Trân trọng,<br/><strong>PEMS - FPT University</strong></p>',
   '[PEMS] {{campusName}} cannot accept request {{requestCode}}', '<p style="margin:0 0 16px;color:#334155">Dear <strong>{{recipientName}}</strong>,</p><p style="margin:0 0 14px;color:#334155;line-height:1.65">We are sorry to say that <strong>{{campusName}}</strong> cannot host your delegation for the request below. Any other campuses in the same request are unaffected by this decision.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;margin:18px 0;border:1px solid #dbe4ee;border-radius:8px"><tbody><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Request code</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{requestCode}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Delegation</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{delegationName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Campus</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{campusName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%">Planned time</td><td style="padding:10px 14px;font-weight:600;color:#334155">{{plannedTime}}</td></tr></tbody></table><div style="margin:20px 0;padding:16px 18px;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px"><p style="margin:0 0 8px;font-weight:700;color:#9a3412">Reason</p><p style="margin:0;color:#334155;line-height:1.6">{{reason}}</p></div><p style="margin:0 0 14px;color:#334155;line-height:1.65">You can edit and resubmit the request from your visit request page. Please note that a resubmitted schedule must start at least 72 hours after it is sent.</p><div style="margin:20px 0 0;padding:14px 16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px"><p style="margin:0 0 8px;font-size:12px;font-weight:700;color:#475569">Sender</p><p style="margin:0;line-height:1.65;color:#334155"><strong>{{senderName}}</strong><br/>{{senderRole}}<br/>{{senderDepartment}}<br/>{{senderEmail}}</p></div><p style="margin:22px 0 0;color:#64748b;font-size:12px;line-height:1.6">Best regards,<br/><strong>PEMS - FPT University</strong></p>',
   'HTML', 'recipientName,requestCode,delegationName,campusName,plannedTime,reason,senderName,senderRole,senderEmail,senderPhone,senderDepartment,senderCampus', CURRENT_TIMESTAMP, NULL, NULL, NULL),
  (70033, 'VISIT_CONTACT_INVITATION_EXPIRED', 'Thông báo lời mời đầu mối đã hết hạn', 'VISIT_REQUEST', NULL, 'Gửi người đăng ký khi lời mời xác nhận đầu mối liên hệ hết hạn mà chưa được phản hồi. Không phải thông báo từ chối đơn.', 'ACTIVE',
   '[PEMS] Lời mời đầu mối cho yêu cầu {{requestCode}} đã hết hạn', '<p style="margin:0 0 16px;color:#334155">Kính gửi <strong>{{recipientName}}</strong>,</p><p style="margin:0 0 14px;color:#334155;line-height:1.65">Lời mời xác nhận vai trò đầu mối liên hệ mà hệ thống đã gửi tới địa chỉ <strong>{{pendingContactEmailMasked}}</strong> đã hết hạn mà chưa được phản hồi.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;margin:18px 0;border:1px solid #dbe4ee;border-radius:8px"><tbody><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Mã yêu cầu</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{requestCode}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Đoàn</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{delegationName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Cơ sở</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{campusName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%">Địa chỉ được mời</td><td style="padding:10px 14px;font-weight:600;color:#334155">{{pendingContactEmailMasked}}</td></tr></tbody></table><div style="margin:20px 0;padding:16px 18px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px"><p style="margin:0 0 8px;font-weight:700;color:#0f3d67">Việc cần làm</p><p style="margin:0;color:#334155;line-height:1.6">Trong trang chi tiết yêu cầu, Quý vị có thể gửi lại lời mời cho chính địa chỉ này, hoặc chỉ định một đầu mối khác. Liên kết cũ đã không còn sử dụng được.</p></div><div style="margin:20px 0 0;padding:14px 16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px"><p style="margin:0 0 8px;font-size:12px;font-weight:700;color:#475569">Thông tin người gửi</p><p style="margin:0;line-height:1.65;color:#334155"><strong>{{senderName}}</strong><br/>{{senderRole}}<br/>{{senderDepartment}}<br/>{{senderEmail}}</p></div><p style="margin:22px 0 0;color:#64748b;font-size:12px;line-height:1.6">Trân trọng,<br/><strong>PEMS - FPT University</strong></p>',
   '[PEMS] The contact invitation for request {{requestCode}} has expired', '<p style="margin:0 0 16px;color:#334155">Dear <strong>{{recipientName}}</strong>,</p><p style="margin:0 0 14px;color:#334155;line-height:1.65">The invitation to confirm the contact role, sent to <strong>{{pendingContactEmailMasked}}</strong>, has expired without a reply.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;margin:18px 0;border:1px solid #dbe4ee;border-radius:8px"><tbody><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Request code</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{requestCode}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Delegation</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{delegationName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%;border-bottom:1px solid #e5e7eb">Campus</td><td style="padding:10px 14px;font-weight:600;color:#334155;border-bottom:1px solid #e5e7eb">{{campusName}}</td></tr><tr><td style="padding:10px 14px;color:#64748b;width:34%">Invited address</td><td style="padding:10px 14px;font-weight:600;color:#334155">{{pendingContactEmailMasked}}</td></tr></tbody></table><div style="margin:20px 0;padding:16px 18px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px"><p style="margin:0 0 8px;font-weight:700;color:#0f3d67">What to do next</p><p style="margin:0;color:#334155;line-height:1.6">From the request detail page you can send the invitation again to the same address, or name a different contact. The previous link can no longer be used.</p></div><div style="margin:20px 0 0;padding:14px 16px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px"><p style="margin:0 0 8px;font-size:12px;font-weight:700;color:#475569">Sender</p><p style="margin:0;line-height:1.65;color:#334155"><strong>{{senderName}}</strong><br/>{{senderRole}}<br/>{{senderDepartment}}<br/>{{senderEmail}}</p></div><p style="margin:22px 0 0;color:#64748b;font-size:12px;line-height:1.6">Best regards,<br/><strong>PEMS - FPT University</strong></p>',
   'HTML', 'recipientName,requestCode,delegationName,campusName,pendingContactEmailMasked,senderName,senderRole,senderEmail,senderPhone,senderDepartment,senderCampus', CURRENT_TIMESTAMP, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE
  name = VALUES(name), purpose = VALUES(purpose), description = VALUES(description),
  status = 'ACTIVE', subject_vi = VALUES(subject_vi), body_vi = VALUES(body_vi),
  subject_en = VALUES(subject_en), body_en = VALUES(body_en),
  body_format = VALUES(body_format), variables_text = VALUES(variables_text),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO email_contact_policies
  (scope_type, scope_key, requirement, contact_source,
   show_email, show_phone, show_department, show_campus, show_sender,
   heading_vi, heading_en, reply_to_source,
   created_at, created_by, updated_at, updated_by)
VALUES
  ('TEMPLATE', 'VISIT_CAMPUS_REJECTED', 'OPTIONAL', 'CAMPUS_DEFAULT', 1, 1, 0, 1, 0, NULL, NULL, 'NONE', CURRENT_TIMESTAMP, NULL, NULL, NULL),
  ('TEMPLATE', 'VISIT_CONTACT_INVITATION_EXPIRED', 'OPTIONAL', 'CAMPUS_DEFAULT', 1, 1, 0, 1, 0, NULL, NULL, 'NONE', CURRENT_TIMESTAMP, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE
  requirement = VALUES(requirement), contact_source = VALUES(contact_source),
  updated_at = CURRENT_TIMESTAMP;
