namespace PEMS.Application.Delegations.Queries.GetVisitProcessDetail;

public sealed class VisitProcessDetailDto
{
    public ulong VisitRequestId { get; set; }
    public ulong VisitInstanceId { get; set; }
    public string DelegationName { get; set; } = default!;
    public string InstanceStatus { get; set; } = default!;
    public DateTime PlannedStartAt { get; set; }
    public DateTime PlannedEndAt { get; set; }
    public string? CampusName { get; set; }
    public ulong? HostUserId { get; set; }
    public string? HostName { get; set; }

    /// <summary>HOST | STAFF_LEADER | HO | VISITOR_OWNER | IC_SUPPORT | DEPT_SUPPORT | STUDENT | NONE.</summary>
    public string Relation { get; set; } = "NONE";

    /// <summary>True only for the official host while the instance is in the editable prep window.</summary>
    public bool CanEditBefore { get; set; }

    public List<AgendaItemDto> Agenda { get; set; } = new();
}

public sealed class AgendaItemDto
{
    public ulong AgendaId { get; set; }
    public string Title { get; set; } = default!;
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public string? Description { get; set; }
    public string? Location { get; set; }

    /// <summary>Set when this row was generated by applying an agenda template; the source template is
    /// traced via visit_agendas → agenda_template_items → agenda_templates. Null for manual rows.</summary>
    public ulong? SourceTemplateItemId { get; set; }

    /// <summary>The concrete user assigned to run this agenda item (visit_agendas.responsible_user_id).
    /// Null when unassigned. This is a REAL user — distinct from the template's suggested role label.</summary>
    public ulong? ResponsibleUserId { get; set; }
    public string? ResponsibleUserName { get; set; }
    public string? ResponsibleUserEmail { get; set; }

    /// <summary>The suggested role text from the source template item (agenda_template_items.
    /// responsible_role_label), e.g. "IC Host". Display-only hint; NOT a person. Null for manual rows
    /// or when the source template item has no label.</summary>
    public string? TemplateResponsibleRoleLabel { get; set; }
}
