<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\PEMS.Domain\PEMS.Domain.csproj" />
		<ProjectReference Include="..\PEMS.Application\PEMS.Application.csproj" />
	</ItemGroup>
</Project>