import type { ResolvedCampusVisit } from '../api/visitRequestV2Api';

/** Shared read-model fixture for the v2 detail component tests. */
export const campusFixture = (overrides: Partial<ResolvedCampusVisit> = {}): ResolvedCampusVisit => ({
  visitInstanceId: 10,
  campusId: 1,
  campusCode: 'HN',
  campusName: 'FPTU Hà Nội',
  plannedStartAt: '2026-08-01T09:00:00',
  plannedEndAt: '2026-08-01T11:30:00',
  timezone: 'Asia/Ho_Chi_Minh',
  // A CAMPUS instance is never "APPROVED" — that value belongs to visit_requests.status. The
  // decided-and-hosted state of an instance is ASSIGNED (see the visit_request_campuses enum).
  instanceStatus: 'ASSIGNED',
  currentHostUserId: 5,
  currentHostName: 'Host Hà Nội',
  decidedByUserId: 6,
  decidedByName: 'Leader HN',
  decidedAt: '2026-07-20T10:00:00',
  decisionActorRole: 'STAFF_LEADER',
  decisionNote: 'OK',
  cancelledByUserId: null,
  cancelledByName: null,
  cancelledAt: null,
  cancellationActorType: null,
  cancellationSource: null,
  cancellationReason: null,
  delegationName: 'Đoàn ĐH ABC',
  visitType: 'MEETING',
  visitTypeOther: null,
  purpose: 'Trao đổi hợp tác',
  workingContent: 'Nội dung làm việc HN',
  visitors: [
    { guestMemberId: 1, memberType: 'VISITOR', fullName: 'Khách Một', organization: 'ĐH ABC', jobTitle: 'GV', nationality: 'VN', displayOrder: 1 },
  ],
  supportMembers: [],
  operationalContact: { fullName: 'Đầu Mối HN', organization: 'ĐH ABC', phone: '+84912345678', email: 'dm@x.vn' },
  workingLanguage: 'VI',
  transportationNote: null,
  mediaConsentStatus: 'DECLINED',
  mediaConsentNote: null,
  noteToFptu: null,
  formRevision: 2,
  approvalRevision: 1,
  rowVersion: 3,
  activeAmendment: null,
  ...overrides,
});
