using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using PEMS.Application.Common.Exceptions;
using PEMS.Application.Common.Files;
using PEMS.Application.Common.Interfaces;
using PEMS.Application.Emails.Common;
using PEMS.Application.Emails.Idempotency;

namespace PEMS.Application.Delegations.SetupProgressEmail;

/// <summary>
/// Sends the Host's setup-progress message, as the composer is holding it.
///
/// <para>
/// The subject, body, recipients and attachments come from the client, which is what changed: they used to
/// come from an <c>email_drafts</c> row the server had written. The guards did not change — every one of
/// them ran at send time before, because a draft row was never evidence of anything current, and they all
/// still run here.
/// </para>
/// <para>
/// A parameterless class rather than a positional record, and a response with a settable
/// <c>Success</c>/<c>Message</c>, because the idempotency behaviour constructs both reflectively when it
/// replays a duplicate.
/// </para>
/// </summary>
public sealed class SendVisitSetupProgressEmailCommand
    : IRequest<SendVisitSetupProgressEmailResponse>, IIdempotentEmailSend
{
    public string OperationCode => EmailSendOperations.VisitSetupProgress;

    /// <summary>
    /// What makes this send itself: the instance, the words, and the three recipient groups. A retry of the
    /// same click is recognised and replayed; editing the body or the address list is a DIFFERENT message
    /// and is refused under the same key rather than answered "already sent".
    ///
    /// <para>
    /// The attachment set is described too — the report is regenerated by "đồng bộ" and gets a new file id,
    /// so a send after a sync is genuinely a different message and must not be mistaken for a replay of the
    /// one before it.
    /// </para>
    /// </summary>
    public void DescribeRequest(EmailSendFingerprintBuilder builder) =>
        builder.Id("instance", VisitInstanceId)
               .Text("subject", Subject)
               .Text("body", BodyHtml)
               .Text("language", LanguageCode)
               .Recipients("recipients", Recipients?.Select(r => $"{r?.RecipientType}:{r?.Email}"))
               .Text("attachments", Attachments is null
                   ? null
                   : string.Join(",", Attachments.Where(a => a is not null).Select(a => a.FileId.ToString())));

    /// <summary>Route values, assigned by the controller — never read from the body.</summary>
    public ulong VisitRequestId { get; set; }
    public ulong VisitInstanceId { get; set; }

    public string Subject { get; set; } = string.Empty;
    public string BodyHtml { get; set; } = string.Empty;
    public string? LanguageCode { get; set; }

    public List<EmailComposeRecipientInput> Recipients { get; set; } = new();

    /// <summary>
    /// Every file to attach, as the composer is holding them — possibly none.
    ///
    /// <para>
    /// The Schedule Report is attached by default and the Host may remove it, so an empty list is a valid
    /// message rather than an incomplete one. When the report IS here it is still identified by
    /// <c>documents</c> rather than by its position or its name (see <see cref="SetupProgressReport"/>) —
    /// not to enforce its presence, but so the extra readability check below is applied to the real report
    /// and not to any file that happens to be named like one.
    /// </para>
    /// </summary>
    public List<EmailComposeAttachmentInput> Attachments { get; set; } = new();
}

public sealed class SendVisitSetupProgressEmailResponse : IEmailSendResult
{
    public ulong? SentEmailId { get; set; }

    /// <summary>SENT | FAILED | QUEUED. Never DELIVERED — PEMS has no delivery webhook.</summary>
    public string Status { get; set; } = "QUEUED";

    public bool Success { get; set; }
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// Why this is not simply <c>POST /api/Emails/send</c>.
///
/// <para>
/// The generic send asks one question — are you signed in — and that can be true of a message that must no
/// longer go out. Between opening the composer and pressing send, the campus can be cancelled, the visit
/// can start, or the delegation can be handed to a different host. So the visit guards run again here,
/// against the database, at the moment of sending.
/// </para>
/// <para>
/// What this no longer does is require the Schedule Report. It used to refuse any send whose attachments
/// did not include one, on the reasoning that the body told the guest a report was attached — so the body
/// stopped saying that, and the report became what it always should have been: something prepared for the
/// Host and offered to them, which they may remove. The refusal cost more than it protected. It fired on
/// the Host who deliberately deleted the PDF, and it fired on the Host who never had one because Google
/// Drive was unreachable, and in both cases it blocked a message whose actual content was complete.
/// </para>
/// <para>
/// Nothing about attachment SECURITY changed with it. Every attached file still goes through
/// <c>EmailComposeWriter.ValidateAndLoadFilesAsync</c> (the file must exist and must belong to the sender)
/// and <c>DirectEmailSender</c>'s fail-closed readability check, so a crafted request naming somebody
/// else's file is refused exactly as before — those rules never depended on this one.
/// </para>
/// </summary>
public sealed class SendVisitSetupProgressEmailCommandHandler
    : IRequestHandler<SendVisitSetupProgressEmailCommand, SendVisitSetupProgressEmailResponse>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    private readonly IDirectEmailSender _sender;
    private readonly IFileStorageService _storage;
    private readonly IGoogleDriveStorageService _drive;

    public SendVisitSetupProgressEmailCommandHandler(
        IApplicationDbContext db,
        ICurrentUserService currentUser,
        IDirectEmailSender sender,
        IFileStorageService storage,
        IGoogleDriveStorageService drive)
    {
        _db = db;
        _currentUser = currentUser;
        _sender = sender;
        _storage = storage;
        _drive = drive;
    }

    public async Task<SendVisitSetupProgressEmailResponse> Handle(
        SendVisitSetupProgressEmailCommand request, CancellationToken cancellationToken)
    {
        if (!_currentUser.IsAuthenticated || _currentUser.UserId is not { } userId)
            throw new ForbiddenException();

        // Re-authorisation, at send time, from the database — not from whatever the browser was told when
        // the composer opened.
        var instance = await VisitSetupProgressEmailGuard.ResolveHostInstanceAsync(
            _db, request.VisitRequestId, request.VisitInstanceId, userId, cancellationToken);

        // The report, IF the Host kept it. No report is a complete message, so there is nothing to check.
        if (await FindAttachedReportAsync(request, instance.VisitRequestId, cancellationToken) is { } report)
        {
            // Having the file id is not having the FILE. DirectEmailSender refuses an unreadable file for
            // every attachment, but this one earns its own message: it is the attachment this screen
            // generated and offers to rebuild, so the useful answer names it and points at that button
            // rather than at a file the Host has never heard of.
            //
            // Refused rather than regenerated. Regenerating here would attach a report built from setup
            // data newer than the tables already in this body, so the message would describe one state and
            // carry another — the exact contradiction "Đồng bộ dữ liệu mới nhất" exists to prevent by
            // rebuilding both halves together.
            var probe = await StoredFileProbe.ProbeAsync(
                _db, _storage, _drive, report.FileId, cancellationToken);
            if (!probe.IsAvailable)
                throw new ValidationException(
                    $"Không gửi được: {StoredFileProbe.Describe(probe.Availability)}. "
                    + "Bấm “Đồng bộ dữ liệu mới nhất” để tạo lại Báo cáo Lịch trình, "
                    + "hoặc gỡ tệp báo cáo ra khỏi email rồi gửi lại. "
                    + $"(Mã lỗi: {probe.ErrorCode})");
        }

        var result = await _sender.SendAsync(
            new DirectEmailRequest(
                Subject: request.Subject,
                BodyContent: request.BodyHtml,
                BodyFormat: Domain.Enums.EmailBodyFormat.HTML.ToString(),
                Recipients: request.Recipients,
                Attachments: request.Attachments,
                RelatedType: SetupProgressReport.RelatedType,
                RelatedId: instance.VisitInstanceId),
            userId,
            cancellationToken);

        return new SendVisitSetupProgressEmailResponse
        {
            SentEmailId = result.SentEmailId,
            Status = result.Status,
            Success = result.Success,
            Message = result.Message,
        };
    }

    /// <summary>
    /// This visit's Schedule Report among the attachments, or null when the message carries none.
    ///
    /// <para>
    /// Each attached file is offered to <see cref="SetupProgressReport.FindReportAsync"/>, which answers
    /// from <c>documents</c>. Null therefore covers three different messages — the Host removed the
    /// report, the report was never produced, the attached file merely looks like one — and treats them
    /// identically, which is correct now that none of them is a reason to refuse. What the identification
    /// still buys is the targeted readability check above: a file the Host uploaded and named
    /// <c>PEMS_Schedule_Report_….pdf</c>, or a genuine report belonging to a DIFFERENT delegation, does not
    /// get the "bấm Đồng bộ dữ liệu mới nhất" advice, because rebuilding this visit's report would do
    /// nothing for it. It is still validated as an ordinary attachment by the shared sender.
    /// </para>
    /// </summary>
    private async Task<SetupProgressReportAttachment?> FindAttachedReportAsync(
        SendVisitSetupProgressEmailCommand request, ulong visitRequestId, CancellationToken cancellationToken)
    {
        foreach (var attachment in request.Attachments ?? new List<EmailComposeAttachmentInput>())
        {
            if (attachment is null) continue;
            var found = await SetupProgressReport.FindReportAsync(
                _db, attachment.FileId, visitRequestId, cancellationToken);
            if (found is { } report) return report;
        }

        return null;
    }
}
