using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using PEMS.Application.Common.Exceptions;
using PEMS.Application.Common.Files;
using PEMS.Application.Common.Interfaces;
using PEMS.Application.Emails.Common;
using PEMS.Application.Emails.Idempotency;

namespace PEMS.Application.Delegations.SetupProgressEmail;

/// <summary>
/// Sends the Host's setup-progress message, as the composer is holding it.
///
/// <para>
/// The subject, body, recipients and attachments come from the client, which is what changed: they used to
/// come from an <c>email_drafts</c> row the server had written. The guards did not change — every one of
/// them ran at send time before, because a draft row was never evidence of anything current, and they all
/// still run here.
/// </para>
/// <para>
/// A parameterless class rather than a positional record, and a response with a settable
/// <c>Success</c>/<c>Message</c>, because the idempotency behaviour constructs both reflectively when it
/// replays a duplicate.
/// </para>
/// </summary>
public sealed class SendVisitSetupProgressEmailCommand
    : IRequest<SendVisitSetupProgressEmailResponse>, IIdempotentEmailSend
{
    public string OperationCode => EmailSendOperations.VisitSetupProgress;

    /// <summary>
    /// What makes this send itself: the instance, the words, and the three recipient groups. A retry of the
    /// same click is recognised and replayed; editing the body or the address list is a DIFFERENT message
    /// and is refused under the same key rather than answered "already sent".
    ///
    /// <para>
    /// The attachment set is described too — the report is regenerated by "đồng bộ" and gets a new file id,
    /// so a send after a sync is genuinely a different message and must not be mistaken for a replay of the
    /// one before it.
    /// </para>
    /// </summary>
    public void DescribeRequest(EmailSendFingerprintBuilder builder) =>
        builder.Id("instance", VisitInstanceId)
               .Text("subject", Subject)
               .Text("body", BodyHtml)
               .Text("language", LanguageCode)
               .Recipients("recipients", Recipients?.Select(r => $"{r?.RecipientType}:{r?.Email}"))
               .Text("attachments", Attachments is null
                   ? null
                   : string.Join(",", Attachments.Where(a => a is not null).Select(a => a.FileId.ToString())));

    /// <summary>Route values, assigned by the controller — never read from the body.</summary>
    public ulong VisitRequestId { get; set; }
    public ulong VisitInstanceId { get; set; }

    public string Subject { get; set; } = string.Empty;
    public string BodyHtml { get; set; } = string.Empty;
    public string? LanguageCode { get; set; }

    public List<EmailComposeRecipientInput> Recipients { get; set; } = new();

    /// <summary>
    /// Every file to attach, the mandatory Schedule Report among them. The report is identified by
    /// <c>documents</c>, not by its position or its name — see <see cref="SetupProgressReport"/>.
    /// </summary>
    public List<EmailComposeAttachmentInput> Attachments { get; set; } = new();
}

public sealed class SendVisitSetupProgressEmailResponse : IEmailSendResult
{
    public ulong? SentEmailId { get; set; }

    /// <summary>SENT | FAILED | QUEUED. Never DELIVERED — PEMS has no delivery webhook.</summary>
    public string Status { get; set; } = "QUEUED";

    public bool Success { get; set; }
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// Why this is not simply <c>POST /api/Emails/send</c>.
///
/// <para>
/// The generic send asks one question — are you signed in — and that can be true of a message that must no
/// longer go out. Between opening the composer and pressing send, the campus can be cancelled, the visit
/// can start, or the delegation can be handed to a different host. So the visit guards run again here,
/// against the database, at the moment of sending; and the message must still carry the report, because the
/// body tells the guest a schedule report is attached.
/// </para>
/// </summary>
public sealed class SendVisitSetupProgressEmailCommandHandler
    : IRequestHandler<SendVisitSetupProgressEmailCommand, SendVisitSetupProgressEmailResponse>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    private readonly IDirectEmailSender _sender;
    private readonly IFileStorageService _storage;
    private readonly IGoogleDriveStorageService _drive;

    public SendVisitSetupProgressEmailCommandHandler(
        IApplicationDbContext db,
        ICurrentUserService currentUser,
        IDirectEmailSender sender,
        IFileStorageService storage,
        IGoogleDriveStorageService drive)
    {
        _db = db;
        _currentUser = currentUser;
        _sender = sender;
        _storage = storage;
        _drive = drive;
    }

    public async Task<SendVisitSetupProgressEmailResponse> Handle(
        SendVisitSetupProgressEmailCommand request, CancellationToken cancellationToken)
    {
        if (!_currentUser.IsAuthenticated || _currentUser.UserId is not { } userId)
            throw new ForbiddenException();

        // Re-authorisation, at send time, from the database — not from whatever the browser was told when
        // the composer opened.
        var instance = await VisitSetupProgressEmailGuard.ResolveHostInstanceAsync(
            _db, request.VisitRequestId, request.VisitInstanceId, userId, cancellationToken);

        var report = await FindMandatoryReportAsync(request, instance.VisitRequestId, cancellationToken);

        // Having the file id is not having the FILE. The attachment loader refuses an unreadable file for
        // every attachment, but this one earns its own message: the body promises a schedule report, so the
        // useful answer names the report and points at the button that rebuilds it.
        //
        // Refused rather than regenerated. Regenerating here would attach a report built from setup data
        // newer than the tables already in this body, so the message would describe one state and carry
        // another — the exact contradiction "Đồng bộ dữ liệu mới nhất" exists to prevent by rebuilding both
        // halves together.
        var probe = await StoredFileProbe.ProbeAsync(
            _db, _storage, _drive, report.FileId, cancellationToken);
        if (!probe.IsAvailable)
            throw new ValidationException(
                $"Không gửi được: {StoredFileProbe.Describe(probe.Availability)}. "
                + "Bấm “Đồng bộ dữ liệu mới nhất” để tạo lại Báo cáo Lịch trình, rồi gửi lại. "
                + $"(Mã lỗi: {probe.ErrorCode})");

        var result = await _sender.SendAsync(
            new DirectEmailRequest(
                Subject: request.Subject,
                BodyContent: request.BodyHtml,
                BodyFormat: Domain.Enums.EmailBodyFormat.HTML.ToString(),
                Recipients: request.Recipients,
                Attachments: request.Attachments,
                RelatedType: SetupProgressReport.RelatedType,
                RelatedId: instance.VisitInstanceId),
            userId,
            cancellationToken);

        return new SendVisitSetupProgressEmailResponse
        {
            SentEmailId = result.SentEmailId,
            Status = result.Status,
            Success = result.Success,
            Message = result.Message,
        };
    }

    /// <summary>
    /// The Schedule Report among the attachments, or a refusal.
    ///
    /// <para>
    /// Every attached file is offered to <see cref="SetupProgressReport.FindReportAsync"/>, which answers
    /// from <c>documents</c> — so the report cannot be satisfied by a file the Host uploaded and named to
    /// look like one, and cannot be satisfied by a genuine report belonging to a DIFFERENT delegation.
    /// </para>
    /// </summary>
    private async Task<SetupProgressReportAttachment> FindMandatoryReportAsync(
        SendVisitSetupProgressEmailCommand request, ulong visitRequestId, CancellationToken cancellationToken)
    {
        foreach (var attachment in request.Attachments ?? new List<EmailComposeAttachmentInput>())
        {
            if (attachment is null) continue;
            var found = await SetupProgressReport.FindReportAsync(
                _db, attachment.FileId, visitRequestId, cancellationToken);
            if (found is { } report) return report;
        }

        throw new ValidationException(
            "Email này bắt buộc phải đính kèm Báo cáo Lịch trình của chuyến thăm. "
            + "Bấm “Đồng bộ dữ liệu mới nhất” để tạo lại báo cáo, rồi gửi lại.");
    }
}
